suites:
  main:
    namespace: Appocular\Clients
    psr4_prefix: Appocular\Clients
    src_path: src

extensions:
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - php
    output:
      php: coverage/spec.cov
    whitelist:
      - src
formatter.name: pretty
